/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ada.apps;

import com.ada.desks.R;



public final class Res {
	public static final R.anim anim = new R.anim();
	public static final R.array array = new R.array();
	public static final R.attr attr = new R.attr();
	// public static final R.bool bool = new R.bool();
	public static final R.color color = new R.color();
	public static final R.dimen dimen = new R.dimen();
	public static final R.drawable drawable = new R.drawable();
	public static final R.id id = new R.id();
	// public static final R.integer integer = new R.integer();
	public static final R.layout layout = new R.layout();
	// public static final R.plurals plurals = new R.plurals();
	// public static final R.raw raw = new R.raw();
	public static final R.string string = new R.string();
	public static final R.style style = new R.style();
	 public static final R.styleable styleable= new R.styleable();
	public static final R.xml xml = new R.xml();
	public static final R.menu menu = new R.menu();
	//public static final R.styleable =null;
}
