<?xml version="1.0" encoding="utf-8"?>
<Database Name="webwork" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=webwork;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="webworkConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Message" Member="Message">
    <Type Name="Message" Id="ID1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Member="Message1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="News">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewsContent" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="PupTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NewsSubType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NewsSubType_News" Member="NewsSubType1" ThisKey="NewsSubType" OtherKey="ID" Type="NewsSubType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsSubType" Member="NewsSubType">
    <Type Name="NewsSubType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsSubTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewsType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NewsSubType_News" Member="News" ThisKey="ID" OtherKey="NewsSubType" Type="News" />
      <Association Name="NewsType_NewsSubType" Member="NewsType1" ThisKey="NewsType" OtherKey="ID" Type="NewsType" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.NewsType" Member="NewsType">
    <Type Name="NewsType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PubTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NewsType_NewsSubType" Member="NewsSubType" ThisKey="ID" OtherKey="NewsType" Type="NewsSubType" />
    </Type>
  </Table>
  <Function Name="dbo.PageMessage" Method="PageMessage">
    <Parameter Name="curpage" Type="System.Int32" DbType="Int" />
    <Parameter Name="pagesize" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>