<?xml version="1.0" encoding="utf-8"?>
<Database Name="work" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\work.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="workConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Department">
    <Type Name="Department">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Department_Major" Member="Major" ThisKey="ID" OtherKey="Type" Type="Major" />
      <Association Name="School_Department" Member="School" ThisKey="Type" OtherKey="ID" Type="School" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Major" Member="Major">
    <Type Name="Major">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Major_SchoolClass" Member="SchoolClass" ThisKey="ID" OtherKey="Type" Type="SchoolClass" />
      <Association Name="Department_Major" Member="Department" ThisKey="Type" OtherKey="ID" Type="Department" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.School" Member="School">
    <Type Name="School">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="School_Department" Member="Department" ThisKey="ID" OtherKey="Type" Type="Department" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolClass" Member="SchoolClass">
    <Type Name="SchoolClass">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Major_SchoolClass" Member="Major" ThisKey="Type" OtherKey="ID" Type="Major" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserType_User" Member="UserType" ThisKey="Type" OtherKey="ID" Type="UserType" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.UserType" Member="UserType">
    <Type Name="UserType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="UserType_User" Member="User" ThisKey="ID" OtherKey="Type" Type="User" />
    </Type>
  </Table>
</Database>