//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2009/6/14 9:51:12
namespace cng1985.LocalModle
{
    
    /// <summary>
    /// 架构中不存在 WORKEntities 的注释。
    /// </summary>
    public partial class WORKEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“WORKEntities”部分中的连接字符串初始化新 WORKEntities 对象。
        /// </summary>
        public WORKEntities() : 
                base("name=WORKEntities", "WORKEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 WORKEntities 对象。
        /// </summary>
        public WORKEntities(string connectionString) : 
                base(connectionString, "WORKEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 WORKEntities 对象。
        /// </summary>
        public WORKEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "WORKEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Address 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Address> Address
        {
            get
            {
                if ((this._Address == null))
                {
                    this._Address = base.CreateQuery<Address>("[Address]");
                }
                return this._Address;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Address> _Address;
        /// <summary>
        /// 架构中不存在 City 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<City> City
        {
            get
            {
                if ((this._City == null))
                {
                    this._City = base.CreateQuery<City>("[City]");
                }
                return this._City;
            }
        }
        private global::System.Data.Objects.ObjectQuery<City> _City;
        /// <summary>
        /// 架构中不存在 College 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<College> College
        {
            get
            {
                if ((this._College == null))
                {
                    this._College = base.CreateQuery<College>("[College]");
                }
                return this._College;
            }
        }
        private global::System.Data.Objects.ObjectQuery<College> _College;
        /// <summary>
        /// 架构中不存在 Contact 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Contact> Contact
        {
            get
            {
                if ((this._Contact == null))
                {
                    this._Contact = base.CreateQuery<Contact>("[Contact]");
                }
                return this._Contact;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Contact> _Contact;
        /// <summary>
        /// 架构中不存在 CountryRegion 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CountryRegion> CountryRegion
        {
            get
            {
                if ((this._CountryRegion == null))
                {
                    this._CountryRegion = base.CreateQuery<CountryRegion>("[CountryRegion]");
                }
                return this._CountryRegion;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CountryRegion> _CountryRegion;
        /// <summary>
        /// 架构中不存在 Department 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Department> Department
        {
            get
            {
                if ((this._Department == null))
                {
                    this._Department = base.CreateQuery<Department>("[Department]");
                }
                return this._Department;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Department> _Department;
        /// <summary>
        /// 架构中不存在 Employee 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Employee> Employee
        {
            get
            {
                if ((this._Employee == null))
                {
                    this._Employee = base.CreateQuery<Employee>("[Employee]");
                }
                return this._Employee;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Employee> _Employee;
        /// <summary>
        /// 架构中不存在 EmployeeAddress 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EmployeeAddress> EmployeeAddress
        {
            get
            {
                if ((this._EmployeeAddress == null))
                {
                    this._EmployeeAddress = base.CreateQuery<EmployeeAddress>("[EmployeeAddress]");
                }
                return this._EmployeeAddress;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EmployeeAddress> _EmployeeAddress;
        /// <summary>
        /// 架构中不存在 Major 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Major> Major
        {
            get
            {
                if ((this._Major == null))
                {
                    this._Major = base.CreateQuery<Major>("[Major]");
                }
                return this._Major;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Major> _Major;
        /// <summary>
        /// 架构中不存在 ProductCategory 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductCategory> ProductCategory
        {
            get
            {
                if ((this._ProductCategory == null))
                {
                    this._ProductCategory = base.CreateQuery<ProductCategory>("[ProductCategory]");
                }
                return this._ProductCategory;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductCategory> _ProductCategory;
        /// <summary>
        /// 架构中不存在 ProductSubcategory 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductSubcategory> ProductSubcategory
        {
            get
            {
                if ((this._ProductSubcategory == null))
                {
                    this._ProductSubcategory = base.CreateQuery<ProductSubcategory>("[ProductSubcategory]");
                }
                return this._ProductSubcategory;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductSubcategory> _ProductSubcategory;
        /// <summary>
        /// 架构中不存在 Province 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Province> Province
        {
            get
            {
                if ((this._Province == null))
                {
                    this._Province = base.CreateQuery<Province>("[Province]");
                }
                return this._Province;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Province> _Province;
        /// <summary>
        /// 架构中不存在 School 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<School> School
        {
            get
            {
                if ((this._School == null))
                {
                    this._School = base.CreateQuery<School>("[School]");
                }
                return this._School;
            }
        }
        private global::System.Data.Objects.ObjectQuery<School> _School;
        /// <summary>
        /// 架构中不存在 Address 的注释。
        /// </summary>
        public void AddToAddress(Address address)
        {
            base.AddObject("Address", address);
        }
        /// <summary>
        /// 架构中不存在 City 的注释。
        /// </summary>
        public void AddToCity(City city)
        {
            base.AddObject("City", city);
        }
        /// <summary>
        /// 架构中不存在 College 的注释。
        /// </summary>
        public void AddToCollege(College college)
        {
            base.AddObject("College", college);
        }
        /// <summary>
        /// 架构中不存在 Contact 的注释。
        /// </summary>
        public void AddToContact(Contact contact)
        {
            base.AddObject("Contact", contact);
        }
        /// <summary>
        /// 架构中不存在 CountryRegion 的注释。
        /// </summary>
        public void AddToCountryRegion(CountryRegion countryRegion)
        {
            base.AddObject("CountryRegion", countryRegion);
        }
        /// <summary>
        /// 架构中不存在 Department 的注释。
        /// </summary>
        public void AddToDepartment(Department department)
        {
            base.AddObject("Department", department);
        }
        /// <summary>
        /// 架构中不存在 Employee 的注释。
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
        /// <summary>
        /// 架构中不存在 EmployeeAddress 的注释。
        /// </summary>
        public void AddToEmployeeAddress(EmployeeAddress employeeAddress)
        {
            base.AddObject("EmployeeAddress", employeeAddress);
        }
        /// <summary>
        /// 架构中不存在 Major 的注释。
        /// </summary>
        public void AddToMajor(Major major)
        {
            base.AddObject("Major", major);
        }
        /// <summary>
        /// 架构中不存在 ProductCategory 的注释。
        /// </summary>
        public void AddToProductCategory(ProductCategory productCategory)
        {
            base.AddObject("ProductCategory", productCategory);
        }
        /// <summary>
        /// 架构中不存在 ProductSubcategory 的注释。
        /// </summary>
        public void AddToProductSubcategory(ProductSubcategory productSubcategory)
        {
            base.AddObject("ProductSubcategory", productSubcategory);
        }
        /// <summary>
        /// 架构中不存在 Province 的注释。
        /// </summary>
        public void AddToProvince(Province province)
        {
            base.AddObject("Province", province);
        }
        /// <summary>
        /// 架构中不存在 School 的注释。
        /// </summary>
        public void AddToSchool(School school)
        {
            base.AddObject("School", school);
        }
    }
    /// <summary>
    /// 架构中不存在 WORKModel.Address 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="Address")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Address : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Address 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Address CreateAddress(int id)
        {
            Address address = new Address();
            address.ID = id;
            return address;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 AddressLine1 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this._AddressLine1;
            }
            set
            {
                this.OnAddressLine1Changing(value);
                this.ReportPropertyChanging("AddressLine1");
                this._AddressLine1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AddressLine1");
                this.OnAddressLine1Changed();
            }
        }
        private string _AddressLine1;
        partial void OnAddressLine1Changing(string value);
        partial void OnAddressLine1Changed();
        /// <summary>
        /// 架构中不存在属性 AddressLine2 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this._AddressLine2;
            }
            set
            {
                this.OnAddressLine2Changing(value);
                this.ReportPropertyChanging("AddressLine2");
                this._AddressLine2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AddressLine2");
                this.OnAddressLine2Changed();
            }
        }
        private string _AddressLine2;
        partial void OnAddressLine2Changing(string value);
        partial void OnAddressLine2Changed();
        /// <summary>
        /// 架构中不存在属性 City 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// 架构中不存在属性 StateProvinceID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> StateProvinceID
        {
            get
            {
                return this._StateProvinceID;
            }
            set
            {
                this.OnStateProvinceIDChanging(value);
                this.ReportPropertyChanging("StateProvinceID");
                this._StateProvinceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StateProvinceID");
                this.OnStateProvinceIDChanged();
            }
        }
        private global::System.Nullable<int> _StateProvinceID;
        partial void OnStateProvinceIDChanging(global::System.Nullable<int> value);
        partial void OnStateProvinceIDChanged();
        /// <summary>
        /// 架构中不存在属性 PostalCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this.ReportPropertyChanging("PostalCode");
                this._PostalCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PostalCode");
                this.OnPostalCodeChanged();
            }
        }
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.City 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="City")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class City : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 City 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static City CreateCity(int id)
        {
            City city = new City();
            city.ID = id;
            return city;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 CityName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName
        {
            get
            {
                return this._CityName;
            }
            set
            {
                this.OnCityNameChanging(value);
                this.ReportPropertyChanging("CityName");
                this._CityName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CityName");
                this.OnCityNameChanged();
            }
        }
        private string _CityName;
        partial void OnCityNameChanging(string value);
        partial void OnCityNameChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 ProvinceID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ProvinceID
        {
            get
            {
                return this._ProvinceID;
            }
            set
            {
                this.OnProvinceIDChanging(value);
                this.ReportPropertyChanging("ProvinceID");
                this._ProvinceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProvinceID");
                this.OnProvinceIDChanged();
            }
        }
        private global::System.Nullable<int> _ProvinceID;
        partial void OnProvinceIDChanging(global::System.Nullable<int> value);
        partial void OnProvinceIDChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.College 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="College")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class College : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 College 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static College CreateCollege(int id)
        {
            College college = new College();
            college.ID = id;
            return college;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 CollegeName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CollegeName
        {
            get
            {
                return this._CollegeName;
            }
            set
            {
                this.OnCollegeNameChanging(value);
                this.ReportPropertyChanging("CollegeName");
                this._CollegeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CollegeName");
                this.OnCollegeNameChanged();
            }
        }
        private string _CollegeName;
        partial void OnCollegeNameChanging(string value);
        partial void OnCollegeNameChanged();
        /// <summary>
        /// 架构中不存在属性 SchoolID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SchoolID
        {
            get
            {
                return this._SchoolID;
            }
            set
            {
                this.OnSchoolIDChanging(value);
                this.ReportPropertyChanging("SchoolID");
                this._SchoolID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SchoolID");
                this.OnSchoolIDChanged();
            }
        }
        private global::System.Nullable<int> _SchoolID;
        partial void OnSchoolIDChanging(global::System.Nullable<int> value);
        partial void OnSchoolIDChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.Contact 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="Contact")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Contact : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Contact 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Contact CreateContact(int id)
        {
            Contact contact = new Contact();
            contact.ID = id;
            return contact;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Title 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 EmailAddress 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this.ReportPropertyChanging("EmailAddress");
                this._EmailAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EmailAddress");
                this.OnEmailAddressChanged();
            }
        }
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// 架构中不存在属性 Phone 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// 架构中不存在属性 PasswordHash 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this.ReportPropertyChanging("PasswordHash");
                this._PasswordHash = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PasswordHash");
                this.OnPasswordHashChanged();
            }
        }
        private string _PasswordHash;
        partial void OnPasswordHashChanging(string value);
        partial void OnPasswordHashChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.CountryRegion 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="CountryRegion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CountryRegion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 CountryRegion 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static CountryRegion CreateCountryRegion(int id)
        {
            CountryRegion countryRegion = new CountryRegion();
            countryRegion.ID = id;
            return countryRegion;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.Department 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="Department")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Department : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Department 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Department CreateDepartment(int id)
        {
            Department department = new Department();
            department.ID = id;
            return department;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 DepartmentName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this._DepartmentName;
            }
            set
            {
                this.OnDepartmentNameChanging(value);
                this.ReportPropertyChanging("DepartmentName");
                this._DepartmentName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DepartmentName");
                this.OnDepartmentNameChanged();
            }
        }
        private string _DepartmentName;
        partial void OnDepartmentNameChanging(string value);
        partial void OnDepartmentNameChanged();
        /// <summary>
        /// 架构中不存在属性 CollegeID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CollegeID
        {
            get
            {
                return this._CollegeID;
            }
            set
            {
                this.OnCollegeIDChanging(value);
                this.ReportPropertyChanging("CollegeID");
                this._CollegeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CollegeID");
                this.OnCollegeIDChanged();
            }
        }
        private global::System.Nullable<int> _CollegeID;
        partial void OnCollegeIDChanging(global::System.Nullable<int> value);
        partial void OnCollegeIDChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.Employee 的注释。
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="Employee")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Employee : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Employee 对象。
        /// </summary>
        /// <param name="employeeID">EmployeeID 的初始值。</param>
        public static Employee CreateEmployee(int employeeID)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            return employee;
        }
        /// <summary>
        /// 架构中不存在属性 EmployeeID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this.ReportPropertyChanging("EmployeeID");
                this._EmployeeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeID");
                this.OnEmployeeIDChanged();
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// 架构中不存在属性 ContactID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ContactID
        {
            get
            {
                return this._ContactID;
            }
            set
            {
                this.OnContactIDChanging(value);
                this.ReportPropertyChanging("ContactID");
                this._ContactID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContactID");
                this.OnContactIDChanged();
            }
        }
        private global::System.Nullable<int> _ContactID;
        partial void OnContactIDChanging(global::System.Nullable<int> value);
        partial void OnContactIDChanged();
        /// <summary>
        /// 架构中不存在属性 LoginID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginID
        {
            get
            {
                return this._LoginID;
            }
            set
            {
                this.OnLoginIDChanging(value);
                this.ReportPropertyChanging("LoginID");
                this._LoginID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LoginID");
                this.OnLoginIDChanged();
            }
        }
        private string _LoginID;
        partial void OnLoginIDChanging(string value);
        partial void OnLoginIDChanged();
        /// <summary>
        /// 架构中不存在属性 ManagerID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ManagerID
        {
            get
            {
                return this._ManagerID;
            }
            set
            {
                this.OnManagerIDChanging(value);
                this.ReportPropertyChanging("ManagerID");
                this._ManagerID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ManagerID");
                this.OnManagerIDChanged();
            }
        }
        private global::System.Nullable<int> _ManagerID;
        partial void OnManagerIDChanging(global::System.Nullable<int> value);
        partial void OnManagerIDChanged();
        /// <summary>
        /// 架构中不存在属性 Title 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// 架构中不存在属性 BirthDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                this.ReportPropertyChanging("BirthDate");
                this._BirthDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BirthDate");
                this.OnBirthDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.EmployeeAddress 的注释。
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// AddressID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="EmployeeAddress")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EmployeeAddress : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 EmployeeAddress 对象。
        /// </summary>
        /// <param name="employeeID">EmployeeID 的初始值。</param>
        /// <param name="addressID">AddressID 的初始值。</param>
        public static EmployeeAddress CreateEmployeeAddress(int employeeID, int addressID)
        {
            EmployeeAddress employeeAddress = new EmployeeAddress();
            employeeAddress.EmployeeID = employeeID;
            employeeAddress.AddressID = addressID;
            return employeeAddress;
        }
        /// <summary>
        /// 架构中不存在属性 EmployeeID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this.ReportPropertyChanging("EmployeeID");
                this._EmployeeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeID");
                this.OnEmployeeIDChanged();
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// 架构中不存在属性 AddressID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID
        {
            get
            {
                return this._AddressID;
            }
            set
            {
                this.OnAddressIDChanging(value);
                this.ReportPropertyChanging("AddressID");
                this._AddressID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddressID");
                this.OnAddressIDChanged();
            }
        }
        private int _AddressID;
        partial void OnAddressIDChanging(int value);
        partial void OnAddressIDChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.Major 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="Major")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Major : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Major 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Major CreateMajor(int id)
        {
            Major major = new Major();
            major.ID = id;
            return major;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 MajorName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorName
        {
            get
            {
                return this._MajorName;
            }
            set
            {
                this.OnMajorNameChanging(value);
                this.ReportPropertyChanging("MajorName");
                this._MajorName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MajorName");
                this.OnMajorNameChanged();
            }
        }
        private string _MajorName;
        partial void OnMajorNameChanging(string value);
        partial void OnMajorNameChanged();
        /// <summary>
        /// 架构中不存在属性 DepartmentID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> DepartmentID
        {
            get
            {
                return this._DepartmentID;
            }
            set
            {
                this.OnDepartmentIDChanging(value);
                this.ReportPropertyChanging("DepartmentID");
                this._DepartmentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DepartmentID");
                this.OnDepartmentIDChanged();
            }
        }
        private global::System.Nullable<int> _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Nullable<int> value);
        partial void OnDepartmentIDChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.ProductCategory 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ProductCategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="ProductCategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductCategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 ProductCategory 对象。
        /// </summary>
        /// <param name="productCategoryID">ProductCategoryID 的初始值。</param>
        public static ProductCategory CreateProductCategory(int productCategoryID)
        {
            ProductCategory productCategory = new ProductCategory();
            productCategory.ProductCategoryID = productCategoryID;
            return productCategory;
        }
        /// <summary>
        /// 架构中不存在属性 ProductCategoryID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryID
        {
            get
            {
                return this._ProductCategoryID;
            }
            set
            {
                this.OnProductCategoryIDChanging(value);
                this.ReportPropertyChanging("ProductCategoryID");
                this._ProductCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductCategoryID");
                this.OnProductCategoryIDChanged();
            }
        }
        private int _ProductCategoryID;
        partial void OnProductCategoryIDChanging(int value);
        partial void OnProductCategoryIDChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.ProductSubcategory 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ProductSubcategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="ProductSubcategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductSubcategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 ProductSubcategory 对象。
        /// </summary>
        /// <param name="productSubcategoryID">ProductSubcategoryID 的初始值。</param>
        public static ProductSubcategory CreateProductSubcategory(int productSubcategoryID)
        {
            ProductSubcategory productSubcategory = new ProductSubcategory();
            productSubcategory.ProductSubcategoryID = productSubcategoryID;
            return productSubcategory;
        }
        /// <summary>
        /// 架构中不存在属性 ProductSubcategoryID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSubcategoryID
        {
            get
            {
                return this._ProductSubcategoryID;
            }
            set
            {
                this.OnProductSubcategoryIDChanging(value);
                this.ReportPropertyChanging("ProductSubcategoryID");
                this._ProductSubcategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductSubcategoryID");
                this.OnProductSubcategoryIDChanged();
            }
        }
        private int _ProductSubcategoryID;
        partial void OnProductSubcategoryIDChanging(int value);
        partial void OnProductSubcategoryIDChanged();
        /// <summary>
        /// 架构中不存在属性 ProductCategoryID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ProductCategoryID
        {
            get
            {
                return this._ProductCategoryID;
            }
            set
            {
                this.OnProductCategoryIDChanging(value);
                this.ReportPropertyChanging("ProductCategoryID");
                this._ProductCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductCategoryID");
                this.OnProductCategoryIDChanged();
            }
        }
        private global::System.Nullable<int> _ProductCategoryID;
        partial void OnProductCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnProductCategoryIDChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.Province 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="Province")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Province : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Province 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Province CreateProvince(int id)
        {
            Province province = new Province();
            province.ID = id;
            return province;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 CountryRegion 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CountryRegion
        {
            get
            {
                return this._CountryRegion;
            }
            set
            {
                this.OnCountryRegionChanging(value);
                this.ReportPropertyChanging("CountryRegion");
                this._CountryRegion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CountryRegion");
                this.OnCountryRegionChanged();
            }
        }
        private global::System.Nullable<int> _CountryRegion;
        partial void OnCountryRegionChanging(global::System.Nullable<int> value);
        partial void OnCountryRegionChanged();
        /// <summary>
        /// 架构中不存在属性 ModifiedDate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
    /// <summary>
    /// 架构中不存在 WORKModel.School 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WORKModel", Name="School")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class School : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 School 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static School CreateSchool(int id)
        {
            School school = new School();
            school.ID = id;
            return school;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 SchoolName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolName
        {
            get
            {
                return this._SchoolName;
            }
            set
            {
                this.OnSchoolNameChanging(value);
                this.ReportPropertyChanging("SchoolName");
                this._SchoolName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SchoolName");
                this.OnSchoolNameChanged();
            }
        }
        private string _SchoolName;
        partial void OnSchoolNameChanging(string value);
        partial void OnSchoolNameChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysChangeTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysChangeTxBsn
        {
            get
            {
                return this._C__sysChangeTxBsn;
            }
            set
            {
                this.OnC__sysChangeTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysChangeTxBsn");
                this._C__sysChangeTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysChangeTxBsn");
                this.OnC__sysChangeTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysChangeTxBsn;
        partial void OnC__sysChangeTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysChangeTxBsnChanged();
        /// <summary>
        /// 架构中不存在属性 C__sysInsertTxBsn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> C__sysInsertTxBsn
        {
            get
            {
                return this._C__sysInsertTxBsn;
            }
            set
            {
                this.OnC__sysInsertTxBsnChanging(value);
                this.ReportPropertyChanging("C__sysInsertTxBsn");
                this._C__sysInsertTxBsn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("C__sysInsertTxBsn");
                this.OnC__sysInsertTxBsnChanged();
            }
        }
        private global::System.Nullable<long> _C__sysInsertTxBsn;
        partial void OnC__sysInsertTxBsnChanging(global::System.Nullable<long> value);
        partial void OnC__sysInsertTxBsnChanged();
    }
}
